export enum ErrorMessage {
  GMAIL_ALREADY_EXITS = 'error.GMAIL_ALREADY_EXITS',
  USER_NAME_ALREADY_EXITS = 'error.USER_NAME_ALREADY_EXITS',
  USER_NAME_INCORRECT = 'error.USER_NAME_INCORRECT',
  PASSWORD_INCORRECT = 'error.PASSWORD_INCORRECT',
}
