export enum ErrorMessage {
  GMAIL_ALREADY_EXITS = 'Gmail alredy exits',
  USER_NAME_ALREADY_EXITS = 'error.USER_NAME_ALREADY_EXITS',
  USER_NAME_INCORRECT = 'error.USER_NAME_INCORRECT',
  PASSWORD_INCORRECT = 'error.PASSWORD_INCORRECT',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  ACCOUNT_NOT_EXISTS = 'error.ACCOUNT_NOT_EXISTS',
  MIN_LENGTH_1 = 'error.MIN_LENGTH_1',
  INVALID_PARAM = 'error.INVALID_PARAM',
  POST_NOT_EXIST = 'error.POST_NOT_EXIST',
  POST_LIKE_EXIST = 'error.POST_LIKE_EXIST',
}
